### ISSUE TITLE
MissingMethodException: No signature of method when using EasyMock Matcher on Groovy test

### ISSUE THREAD

**Issue by xdrop** [easymock/easymock#180] opened 2016-09-08 23:29 UTC
When using EasyMock with groovy tests it fails to `expect()` a matcher if it's on a `boolean` parameter.

**Versions:**
---------------
**Groovy**: 2.4.6
**EasyMock**: 3.4

**Failing example**
-----------------

Demo.java
```java
public class Demo {

    public String test(boolean c)  {
        return "test";
    }

}
```

Groovy test
```java
class DemoTest extends GroovyTestCase {
    void testTest() {

        Demo mock = mock(Demo)

        expect(mock.test(eq(true)))
            .andReturn("test")

        replay(mock)

    }
}
```

Result
```
groovy.lang.MissingMethodException: No signature of method: Demo$$EnhancerByCGLIB$$ff061b6.test() is applicable for argument types: (null) values: [null]
Possible solutions: test(boolean), test(boolean), wait(), use([Ljava.lang.Object;), getAt(java.lang.String), wait(long)
```

While the java version works fine
```java
public class DemoTest extends TestCase {

    @Test
    public void test1() {
        Demo demo = mock(Demo.class);
        expect(demo.test(true))
                .andReturn("test");

        replay(demo);
    }
}
```

**Comment by henri-tremblay** [comment] 2016-09-09 01:50
Interesting. It looks like a Groovy bug. It seems that a boxing occurs on the boolean which causes `eq(Object)` instead of `eq(boolean)` to be called. I will investigate.

**Comment by xdrop** [comment] 2016-09-09 08:36
Yes you are right, don't know if this is intended or not:

```java
public class Demo {

    public void a(boolean a){
        System.out.println("boolean was called");
    }

    public void a(Object a){
        System.out.println("Object was called");
    }

}
```

```groovy
class Groovy {
    static void main(String[] args) {
        def demo = new Demo()
        demo.a(true)
    }
}
```

Output:
`Object was called`

**Comment by Ganet** [comment] 2016-09-09 09:10
Seems like Groovy autowraps primitives, so it is intended behaviour.

Extracted from documentation: http://groovy-lang.org/objectorientation.html 

The solution for your problem is to cast your "true" constant to a boolean primitive in the method call.

```
class Groovy {
    static void main(String[] args) {
        def demo = new Demo()
        demo.a((boolean) true)
    }
}
```
This prints "boolean was called".

**Comment by henri-tremblay** [comment] 2016-09-11 17:52
From my investigation, it seems indeed to be a Groovy bug. Two workarounds are to use `@CompileStatic` or to cast in `(boolean)`.

I've [filled a bug](https://issues.apache.org/jira/browse/GROOVY-7933) and am waiting for their feedback.

**Comment by Ganet** [comment] 2016-09-11 18:53
As I mentioned in my previous post, this is intended behaviour (not a bug) and it is documented. If you open the link regarding primitives and wrappers there is a good explanation regarding the method resolution issue happening here:

![image](https://cloud.githubusercontent.com/assets/1674873/18419727/51e2185e-7859-11e6-895d-6703387c0568.png)

**Comment by xdrop** [comment] 2016-09-11 19:01
@henri-tremblay Have you seen #181 ? Since the issue arises because `eq(Object)` returns null and that can't be autoboxed back to `boolean`, I've added handlers for all the primitives wrapper types (eg. Boolean) which in turn return a non-null value which can be autoboxed back to `boolean`.

This fixes the issue with `eq()` on the Groovy side and shouldn't cause any issues on the Java side. Are there any other methods affected by this?

**Comment by henri-tremblay** [comment] 2016-09-12 02:43
Yes. But if it's a Groovy bug, I would prefer no do it. It will add a lot
of noise because to be logical, I should also add methods for lt, gt and so
on.

**Comment by henri-tremblay** [comment] 2016-09-13 16:14
It should turn out to be a Groovy bug (https://issues.apache.org/jira/browse/GROOVY-7933). However, it seems so old that I might have to workaround it in EasyMock. Since it is impacting only boolean and char, it shouldn't be that annoying I hope.

**Comment by henri-tremblay** [comment] 2016-09-26 00:41
Closed by https://github.com/apache/groovy/pull/424

**Closed** 2016-09-26 00:42 UTC
Labels: bug

**Comment by Anjana-Entropik** [comment] 2019-12-12 06:26
Hey guys, I have the same issue when the method is having parameter as String, I get error as "MissingMethodException: No signature of method is applicable for argument types: (java.lang.string), although I pass parameter value in String, I just do not invoke the method. Could u plz help me

**Comment by jeha03** [comment] 2020-04-20 09:50
Caused by: groovy.lang.MissingMethodException: No signature of method: build_9nru1h51loolqona2e3x55o44.android() is applicable for argument types: (build_9nru1h51loolqona2e3x55o44$_run_closure1) values: [build_9nru1h51loolqona2e3x55o44$_run_closure1@5f63d494]


Help please!

**Comment by henri-tremblay** [comment] 2020-04-20 12:21
@jeha03 Are you on a latest groovy version?

**Comment by wpratima** [comment] 2021-01-27 06:36
> Caused by: groovy.lang.MissingMethodException: No signature of method: build_9nru1h51loolqona2e3x55o44.android() is applicable for argument types: (build_9nru1h51loolqona2e3x55o44$_run_closure1) values: [build_9nru1h51loolqona2e3x55o44$_run_closure1@5f63d494]
> 
> Help, please!

I am facing the same issue after upgrading to the latest Gradle version(6.5). Did you find anything on this?
