### ISSUE TITLE
Expected match not matching

### ISSUE THREAD

**Issue by blazeyellow** [easymock/easymock#209] opened 2018-02-01 15:29 UTC
I have used EasyMock quite a few times and usually thunder through the unit tests but on this occasion I am stuck on the first one.

In my unit test, I have created my nice mock:

        `OrderService orderService = createNiceMock(OrderService.class);`

I have injected said mock into the service I am testing:

        `CartStateRequestProcessor cartStateProcessor = new CartStateRequestProcessorImpl();
        ReflectionTestUtils.setField(cartStateProcessor, "orderService", orderService);`

I have setup my test data and my expectations:
        1.`expect(orderService.findNamedOrderForCustomerNoStatus(eq(CartType.DEFAULT.getType()), eq(anonymousCustomer))).andReturn(inProcessAnonymousCart);`
2. `expect(orderService.findNamedOrderForCustomerNoStatus(eq(CartType.DEFAULT.getType()), eq(customer))).andReturn(inProcessCustomerCart);`

For this tested method, it takes two parameters; a string and a Customer. In both these cases this `CartType` is 'DEFAULT' and as you can probably tell from the Customer params, we have an 'anonymous customer' (denoting a user PRIOR to login) and 'customer' (denoting a user AFTER login). These are DIFFERENT objects.

There are two lines of code that should trigger and match either of these expectations:

1. `inProcessCustomerCart = orderService.findNamedOrderForCustomerNoStatus(cartType.getType(), customer);`
2. `inProcessAnonymousCart = orderService.findNamedOrderForCustomerNoStatus(cartType.getType(), anonymousCustomer);`

The first one matches and gives me my `inProcessAnonymousCart`. The second one does not. It cannot match the second expectation, even though the object identifiers are identical to that of the expectation.

I am lost and I do not know how to proceed. It just does not make sense at all. Any help will be greatly appreciated!

**Comment by blazeyellow** [comment] 2018-02-01 15:39
The `eq()` method led me to check `Customer.equals()` to see which fields are checked for equality, they are `id` and `username`. I have ensured the usernames are different for both the `anonymousCustomer` and the `customer`. Re-tested but still no success.

**Comment by blazeyellow** [comment] 2018-02-01 15:42
Actually...OMG...I am a total dickhead. I should have done this hours ago! Ensuring these usernames are different makes the test success! I will leave this issue here so you can see how much of a dickhead I am. *curtsey*

**Comment by blazeyellow** [comment] 2018-02-01 16:25
During execution, the cart type is "DEFAULT" and I have confirmed this with

`inProcessAnonymousCartType.getType().equals(CartType.DEFAULT.getType())`, which returns `true`. The `customer` has the same `id` and `username` as the one in `expect()`, so this is a match. But this method returns `null` and I cannot figure out why. I have never had this issue with matching, is this a bug?

**Comment by blazeyellow** [comment] 2018-02-01 17:24
I have changed the expect to:

`expect(orderService.findNamedOrderForCustomerNoStatus(anyString(), anyObject(Customer.class))).andReturn(inProcessAnonymousCart);`

Still no luck

**Comment by blazeyellow** [comment] 2018-02-01 17:56
I seem to have it, due to my lack of understanding of `expect()` and most notably `andReturn()` for the various invocations of the method.

I have learnt a little more about EasyMock and no doubt you have found this 'issue' quite entertaining! Thank you!

**Comment by henri-tremblay** [comment] 2018-02-14 22:49
What was the actual issue?

**Comment by henri-tremblay** [comment] 2018-04-06 02:43
Closing since it's not a bug

**Closed by henri-tremblay** 2018-04-06 02:43 UTC
Labels: notabug
