### ISSUE TITLE
easymock 3.5 is aliasing other packages on the classpath

### ISSUE THREAD

**Issue by gautamraj** [easymock/easymock#207] opened 2017-11-16 00:24 UTC
Upgrading from easymock 3.4 -> 3.5 broke our build because easymock seems to be aliasing an older version of jcommander than what we have. More generally it seems like transitive dependencies of easymock are getting packaged into the jar verbatim, instead of being relocated under org.easymock (like asm is).

```
jar tf easymock-3.5.jar | grep .class | grep -v org/easymock | while read line; do dirname $line; done | sort -u

bsh
bsh/classpath
bsh/collection
bsh/commands
bsh/org/objectweb/asm
bsh/reflect
bsh/servlet
bsh/util
com/beust/jcommander
com/beust/jcommander/converters
com/beust/jcommander/defaultprovider
com/beust/jcommander/internal
com/beust/jcommander/validators
com/beust/testng
org/apache/tools/ant
org/apache/tools/ant/attribute
org/apache/tools/ant/dispatch
org/apache/tools/ant/filters
org/apache/tools/ant/filters/util
org/apache/tools/ant/helper
org/apache/tools/ant/input
org/apache/tools/ant/launch
org/apache/tools/ant/listener
org/apache/tools/ant/loader
org/apache/tools/ant/property
org/apache/tools/ant/taskdefs
org/apache/tools/ant/taskdefs/compilers
org/apache/tools/ant/taskdefs/condition
org/apache/tools/ant/taskdefs/cvslib
org/apache/tools/ant/taskdefs/email
org/apache/tools/ant/taskdefs/launcher
org/apache/tools/ant/taskdefs/optional
org/apache/tools/ant/taskdefs/optional/ccm
org/apache/tools/ant/taskdefs/optional/clearcase
org/apache/tools/ant/taskdefs/optional/depend
org/apache/tools/ant/taskdefs/optional/depend/constantpool
org/apache/tools/ant/taskdefs/optional/ejb
org/apache/tools/ant/taskdefs/optional/extension
org/apache/tools/ant/taskdefs/optional/extension/resolvers
org/apache/tools/ant/taskdefs/optional/i18n
org/apache/tools/ant/taskdefs/optional/j2ee
org/apache/tools/ant/taskdefs/optional/javacc
org/apache/tools/ant/taskdefs/optional/javah
org/apache/tools/ant/taskdefs/optional/jlink
org/apache/tools/ant/taskdefs/optional/jsp
org/apache/tools/ant/taskdefs/optional/jsp/compilers
org/apache/tools/ant/taskdefs/optional/native2ascii
org/apache/tools/ant/taskdefs/optional/net
org/apache/tools/ant/taskdefs/optional/pvcs
org/apache/tools/ant/taskdefs/optional/script
org/apache/tools/ant/taskdefs/optional/sos
org/apache/tools/ant/taskdefs/optional/testing
org/apache/tools/ant/taskdefs/optional/unix
org/apache/tools/ant/taskdefs/optional/vss
org/apache/tools/ant/taskdefs/optional/windows
org/apache/tools/ant/taskdefs/rmic
org/apache/tools/ant/types
org/apache/tools/ant/types/mappers
org/apache/tools/ant/types/optional
org/apache/tools/ant/types/optional/depend
org/apache/tools/ant/types/resources
org/apache/tools/ant/types/resources/comparators
org/apache/tools/ant/types/resources/selectors
org/apache/tools/ant/types/selectors
org/apache/tools/ant/types/selectors/modifiedselector
org/apache/tools/ant/types/spi
org/apache/tools/ant/util
org/apache/tools/ant/util/depend
org/apache/tools/ant/util/facade
org/apache/tools/ant/util/java15
org/apache/tools/ant/util/optional
org/apache/tools/ant/util/regexp
org/apache/tools/bzip2
org/apache/tools/mail
org/apache/tools/tar
org/apache/tools/zip
org/testng
org/testng/annotations
org/testng/asserts
org/testng/collections
org/testng/internal
org/testng/internal/annotations
org/testng/internal/collections
org/testng/internal/invokers
org/testng/internal/junit
org/testng/internal/remote
org/testng/internal/thread
org/testng/internal/thread/graph
org/testng/junit
org/testng/log
org/testng/log4testng
org/testng/mustache
org/testng/remote
org/testng/remote/adapter
org/testng/remote/strprotocol
org/testng/reporters
org/testng/reporters/jq
org/testng/reporters/util
org/testng/util
org/testng/xml
org/testng/xml/dom
```

**Comment by henri-tremblay** [comment] 2017-11-16 00:26
Yes. This is a known issue. See #205. I should have release to fix it. I will try today.

**Comment by henri-tremblay** [comment] 2017-11-16 00:27
Duplicate of #205

**Closed by henri-tremblay** 2017-11-16 00:27 UTC
