### ISSUE TITLE
Inconsistant test case, sometimes pass sometime fail

### ISSUE THREAD

**Issue by mkj-git** [easymock/easymock#263] opened 2020-10-23 05:00 UTC
I have this test case

      public void testCacheSyncSingleColumn() throws Exception {
        resetAll();
        String schema = "barcelona_mm";
        String mainTable = "notes";
        String mainCol = "assignee_id";
        String mainColValue = "1";
        String mapQuery = "SELECT firstname AS value FROM #.security_user WHERE security_user_id = ";
        String queryResult = "Support Operations";
        String key = mainTable + "." + mainCol;
        String[] lineA = new String[] { mainTable, mainCol, "security_user", "security_user_id", "firstname" };
        String[] lineB = new String[] { "" };
    
        FileReader fileMock = null;// EasyMock.createMock(FileReader.class);
        CSVReader mockReader = EasyMock.createMock(CSVReader.class);
        connectionFactoryMock = EasyMock.createMock(ConnectionFactory.class);
        cacheSignatureService = new CachedSignatureServiceImpl();
        SignatureDao signatureDaoMock = EasyMock.createMock(SignatureDao.class);
    
        SignatureReader signatureReaderMock = EasyMock.createMock(SignatureReader.class);
    
        setInternalState(cacheSignatureService, SignatureReader.class, signatureReaderMock);
        setInternalState(cacheSignatureService, SignatureDao.class, signatureDaoMock);
        PowerMockito.whenNew(CSVReader.class).withArguments(fileMock).thenReturn(mockReader);

        // ERROR AT THIS LINE
        expect(mockReader.readNext()).andReturn(lineA);
        expect(mockReader.readNext()).andReturn(lineB);
        mockReader.close();
        replayAll();
        JdbcTemplate template = createMock(JdbcTemplate.class);
        expect(template.query(EasyMock.<String> anyObject(), EasyMock.<PreparedStatementSetter> anyObject(),
            EasyMock.<ResultSetExtractor<String>> anyObject())).andReturn(queryResult).anyTimes();
    
        expect(signatureReaderMock.getQuery(EasyMock.anyString(), EasyMock.anyString())).andReturn(mapQuery);
        expect(signatureReaderMock.getRefKey(EasyMock.anyString(), EasyMock.anyString())).andReturn(key);
        expect(signatureReaderMock.getRefKey(EasyMock.anyString(), EasyMock.anyString())).andReturn(key);
        expect(signatureDaoMock.getValue(EasyMock.anyString(), EasyMock.anyString(), EasyMock.anyString(),
            EasyMock.anyString(), EasyMock.anyString())).andReturn(queryResult);
    
        replayAll(signatureReaderMock, signatureDaoMock);
        String result = cacheSignatureService.getValue("source", schema, mainTable, mainCol, mainColValue);
        Assert.assertTrue(result.equals(queryResult));
    
      }

If I run this 10 times, sometime all 10 time it will pass sometime it throw error 

    java.lang.IllegalStateException: 0 matchers expected, 1 recorded.
    This exception usually occurs when matchers are mixed with raw values when recording a method:
        foo(5, eq(6));  // wrong
    You need to use no matcher at all or a matcher for every single param:
        foo(eq(5), eq(6));  // right
        foo(5, 6);  // also right
        at org.easymock.internal.ExpectedInvocation.createMissingMatchers(ExpectedInvocation.java:52)
        at org.easymock.internal.ExpectedInvocation.<init>(ExpectedInvocation.java:41)
        at org.easymock.internal.RecordState.invoke(RecordState.java:51)
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
        at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)

**Comment by henri-tremblay** [comment] 2020-10-24 02:57
Highly surprising. Some questions:

1. Which JVM is it? (version and vendor)
2. Which version of EasyMock
3. Do it still do it without Powermock?
4. The test is all alone when it does that? Nothing going on in parallel?
5. What is happening in setInternalState? Can I have a full test case with all classes to reproduce?
6. Does it still fail when not using EasyMockSupport? I don't know how well it mixes with PowerMock

**Comment by henri-tremblay** [comment] 2020-10-24 02:57
Linked to this: https://stackoverflow.com/questions/64493813/inconsistant-test-case-sometimes-pass-sometime-failnalState

**Comment by henri-tremblay** [comment] 2021-04-12 02:10
Closing this since there is no answer.

**Closed by henri-tremblay** 2021-04-12 02:10 UTC
